# Generated by Django 6.0.2 on 2026-03-07 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_feedbackcompany'),
        ('vacancies', '0004_vacancy_city_vacancy_street'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vacancies', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Favorite Vacancy',
                'verbose_name_plural': 'Favorite Vacancies',
                'constraints': [models.UniqueConstraint(fields=('user', 'vacancy'), name='unique_favorite_vacancy')],
            },
        ),
    ]
