# Generated by Django 6.0.2 on 2026-03-19 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_hiddenvacancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by_users', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hidden Company',
                'verbose_name_plural': 'Hidden Companies',
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_user_hidden_company')],
            },
        ),
    ]
