# Generated by Django 6.0.2 on 2026-03-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('internship', 'Стажировка'), ('contract', 'Контракт'), ('remote', 'Удалённая работа')], default='full_time', max_length=50)),
                ('schedule', models.CharField(choices=[('day', 'Дневные смены'), ('night', 'Ночные смены'), ('flexible', 'Гибкий график'), ('shift', 'Сменный график'), ('remote', 'Удалённо')], default='day', max_length=50)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='companies.company')),
            ],
        ),
    ]
