# Generated by Django 6.0.2 on 2026-03-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='experience_required',
            field=models.CharField(choices=[('with_experience', 'с опытом'), ('without_experience', 'без опыта')], default='with_experience', max_length=50),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_type',
            field=models.CharField(choices=[('weekly', 'раз в неделю'), ('monthly', 'раз в месяц'), ('twice_monthly', '2 раза в месяц'), ('daily', 'ежедневно'), ('hourly', 'по часам'), ('negotiated', 'договорная')], default='monthly', max_length=50),
        ),
    ]
