# Generated by Django 6.0.2 on 2026-03-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancy_experience_from_vacancy_experience_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
