# Generated by Django 6.0.2 on 2026-03-07 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_favoritevacancy'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_views', to='companies.company')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'Resume View',
                'verbose_name_plural': 'Resume Views',
                'constraints': [models.UniqueConstraint(fields=('company', 'resume', 'date'), name='unique_resume_view_per_day')],
            },
        ),
    ]
